# Generated by Django 4.1.4 on 2022-12-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20190907_1432"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
