# Generated by Django 4.1.4 on 2022-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0003_delete_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Film Adı")),
                ("description", models.TextField(verbose_name="Film Açıklaması")),
                ("image", models.CharField(max_length=50, verbose_name="Film Resmi")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme Tarihi"
                    ),
                ),
                ("isPublished", models.BooleanField(default=True)),
            ],
        ),
    ]
